
namespace GraphDecomposition.Utils
{
    public static class ConstructionUtils
    {
        /// <summary>
        /// Get the vertex number from indexes generated by the Bose construction
        /// </summary>
        /// <param name="i">First index</param>
        /// <param name="j">Second index</param>
        /// <returns>Vertex number</returns>
        public static int VertexNumberFromIndexBose(int i, int j)
        {
            return ((i - 1) * 3) + j;
        }

        /// <summary>
        /// Get the vertex number from the indexes generated by the Skolem construction
        /// </summary>
        /// <param name="i">First index</param>
        /// <param name="j">Second index</param>
        /// <returns>Vertex number</returns>
        public static int VertexNumberFromIndexSkolem(int i, int j)
        {
            if (i == 0 && j == 0)
            {
                return 1;
            }

            return ((i - 1) * 3) + j + 1;
        }
    }
}
